force-app/main/default/objects/Account/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FiscalCode__c.field-meta.xml
<CustomField>
    <fullName>FiscalCode__c</fullName>
    <label>Codice Fiscale</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nation__c.field-meta.xml
<CustomField>
    <fullName>Nation__c</fullName>
    <label>Nazione</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IT</fullName>
                <default>true</default>
                <label>Italia</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antartide</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua e Barbuda</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Antille Olandesi</label>
            </value>
            <value>
                <fullName>SA</fullName>
                <label>Arabia Saudita</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaigian</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrein</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgio</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>Bhutan</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Bielorussia</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia-Erzegovina</label>
            </value>
            <value>
                <fullName>BW</fullName>
                <label>Botswana</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VatNumber__c.field-meta.xml
<CustomField>
    <fullName>VatNumber__c</fullName>
    <label>Partita IVA</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <label>Persona Giuridica</label>
</RecordType>

force-app/main/default/classes/ConversioneLead.cls
/*
 *   @TestClass: ConversioneLeadTest
*/
public without sharing class ConversioneLead 
{
    @AuraEnabled(cacheable=true) 
    public static Settings__c getCustomSettings()
    {
        return Settings__c.getOrgDefaults();
    }

    @AuraEnabled
    public static lead GetLead(string recordId) 
    {
        lead lid = new lead();

        /**
            * @description: esegue una query includendo in automatico tutti i campi dell'oggetto
            * @return: lista di risultati di tipo "sObject" generico. È possibile fare il cast del risulta in una lista dell'oggetto specifico
            */ 
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Map<String, Schema.SObjectField> fieldMap = schemaMap.get('Lead').getDescribe().fields.getMap();
        list<string> list_field = new list<string>(fieldMap.keyset());
    
        string qrSelect = 'select '+string.join(list_field , ',');//SELECT con tutti i campi dell'oggetto
        string qrFrom = ' from '+'Lead';//FROM oggetto
        string qrWhere = ' where id = :recordId'; //WHERE filtri query
        string qrOrder = ' order by '; //ORDER BY ordinamento risultati query
        
        //creo una variabile di tipo "Tipo lista<Oggetto>"
        System.Type listType = System.Type.forName('List<Lead>');
        //istanzio una lista vuota del tipo "listType", in modo da poter fare il cast di "result" nel tipo corretto al di fuori del metodo
        List<Lead> resultQuery = (List<Lead>)listType.newInstance();
    
        //aggiungere where/order se correttamente valorizzati nelle variabili
        //---(la lista funziona anche con un solo record: se non trova nulla non va in errore ma restituisce una lista vuota)---
        resultQuery = database.query(qrSelect + qrFrom + qrWhere /*+ qrOrder*/);
        System.debug('result '+resultQuery);
        if(resultQuery.size() > 0 && resultQuery.size() <= 1)
        {
            lid = resultQuery[0];
        }
        else 
        {
            throw new AuraHandledException('Si è verificato un errore');
        }
    
        return lid;
    }
    
    @AuraEnabled
    public static string CheckDataLead(lead lid)
    {
        try 
        {
            string result = 'Non è possibile procedere con la conversione del Lead in quanto non sono compilati correttamente i seguenti campi: ';
            System.debug('lid '+lid);
            
            
            if(lid.Company != null && lid.VatNumber__c == null) {
				result += Lead.Company.getDescribe().getLabel()+', ';
				result += Lead.VatNumber__c.getDescribe().getLabel()+', ';
			}
			else if(lid.Company == null && lid.FiscalCode__c == null) {
				result += Lead.Company.getDescribe().getLabel()+', ';
				result += Lead.FiscalCode__c.getDescribe().getLabel()+', ';
			}
			else if(lid.FirstName == null) {
				result += Lead.FirstName.getDescribe().getLabel()+', ';
			}
			else if( lid.LastName == null) {
				result += Lead.LastName.getDescribe().getLabel()+', ';
			}
			else if(lid.Email == null) {
				result += Lead.Email.getDescribe().getLabel()+', ';
			}
			else if(lid.Nation__c == null) {
				result += Lead.Nation__c.getDescribe().getLabel()+', ';
			}
			else if(lid.Company__c == null) {
				result += Lead.Company__c.getDescribe().getLabel()+', ';
			}
			
		   
            else 
            {
               return result = 'OK';
            }
            result = result.removeEnd(', ');
            return result + '.';
        }
        catch (Exception e) 
        {
            throw new AuraHandledException(e.getMessage());
        }
    }
	

    @AuraEnabled
    public static Account checkAccount(lead lid)
    {
        string result = '';
        String RecordTypeDeveloperName = '';
        Account acc;
        Settings__c sett = Settings__c.getOrgDefaults();

        if(lid.Company==null) RecordTypeDeveloperName = 'PersonAccount'; 
        if(lid.Company<>null) RecordTypeDeveloperName = 'Business';
        /*AND
        Nation__c = Nation__c
        AND (
        Email__c = Email
        OR
        FiscalCode__c = FiscalCode__c
        OR
        VatNumber__c = VatNumber__c*/
        String Nation = lid.Nation__c;
        String Email = lid.Email;
        String FiscalCode = lid.FiscalCode__c;
        String VatNumber = lid.VatNumber__c;
        System.debug(Email);
        System.debug(FiscalCode);
        System.debug(VatNumber);
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Map<String, Schema.SObjectField> fieldMap = schemaMap.get('Account').getDescribe().fields.getMap();
        list<string> list_field = new list<string>(fieldMap.keyset());
    
        string qrSelect = 'select '+string.join(list_field , ',') +', RecordType.DeveloperName, recordType.Name,'+
                            'toLabel(Nation__c)Nazione, toLabel(Company__c)Company';//SELECT con tutti i campi dell'oggetto
        string qrFrom = ' from Account';//FROM oggetto
        string qrWhere = ' where RecordType.DeveloperName = :RecordTypeDeveloperName AND '+ 
                            'Nation__c = :Nation AND '+
                            ((Email != null)?((lid.Company == null)?'(PersonEmail  = :Email ': '(Email__c = :Email ') : '(')+
                            ((FiscalCode != null)?'OR FiscalCode__c = :FiscalCode ': '')+
                            ((VatNumber != null)?'OR VatNumber__c = :VatNumber)': ')'); //WHERE filtri query
        System.debug(qrWhere);
        string qrOrder = ' order by '; //ORDER BY ordinamento risultati query
        
        //creo una variabile di tipo "Tipo lista<Oggetto>"
        System.Type listType = System.Type.forName('List<Account>');
        //istanzio una lista vuota del tipo "listType", in modo da poter fare il cast di "result" nel tipo corretto al di fuori del metodo
        List<Account> resultQuery = (List<Account>)listType.newInstance();
    
        //aggiungere where/order se correttamente valorizzati nelle variabili
        //---(la lista funziona anche con un solo record: se non trova nulla non va in errore ma restituisce una lista vuota)---
        resultQuery = database.query(qrSelect + qrFrom + qrWhere /*+ qrOrder*/);
        System.debug('resutl '+resultQuery);

        if(resultQuery.size() > 0)
        {
            acc = resultQuery[0];
        }

        return acc;
    }

    @AuraEnabled
    public static string ConvertLead(string accountId, lead lid)
    {
        string result = '';

        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(lid.id);

        LeadStatus convertStatus = [SELECT Id, apiname  FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.apiname );

        lc.setAccountId(accountId);
        /*if(lid.Company == null)
        {
            lc.setRelatedPersonAccountId(accountId);
        }*/
        lc.setDoNotCreateOpportunity(false);

        //One or more leads couldn't be converted. Specify an account if relatedPersonAccountId is not null.

        if(!Test.IsRunningTest())Database.LeadConvertResult lcr = Database.convertLead(lc);
        return result;
    }
}