force-app/main/default/objects/Account/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FiscalCode__c.field-meta.xml
<CustomField>
    <fullName>FiscalCode__c</fullName>
    <label>Codice Fiscale</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nation__c.field-meta.xml
<CustomField>
    <fullName>Nation__c</fullName>
    <label>Nazione</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IT</fullName>
                <default>true</default>
                <label>Italia</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antartide</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua e Barbuda</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Antille Olandesi</label>
            </value>
            <value>
                <fullName>SA</fullName>
                <label>Arabia Saudita</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaigian</label>
            </value>
            <value>
                <fullName>BS</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrein</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgio</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>Bhutan</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Bielorussia</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia-Erzegovina</label>
            </value>
            <value>
                <fullName>BW</fullName>
                <label>Botswana</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VatNumber__c.field-meta.xml
<CustomField>
    <fullName>VatNumber__c</fullName>
    <label>Partita IVA</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <label>Persona Giuridica</label>
</RecordType>

force-app/main/default/classes/ConversioneLeadTest.cls
/*
 *   @Class  :   ConversioneLead
*/
@isTest
 public with sharing class ConversioneLeadTest 
{
    @TestSetup
    static void testsetup()
    {
        settings__c sett = new Settings__c();
        insert sett;

        Lead sobj = new Lead(
            FirstName = 'eww',
            LastName = 'test',
            Company__c = '8',// Company
            Company = 'tre',
            Email = 'testff@ftest.it.ewe',   // Email
            FiscalCode__c = null,            // Codice Fiscale
            VatNumber__c = '10810700152',    // Partita IVA
            Nation__c = 'IT'            // Nazione
            );
        insert sobj;

        account sobj2 = new account(
            Name = 'eww',
            Company__c = '1',// Company
            Email__c = 'testff@ftest.it.ewe',   // Email
            FiscalCode__c = null,            // Codice Fiscale
            VatNumber__c = '10810700152',    // Partita IVA
            Nation__c = 'IT',            // Nazione
            recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business').getRecordTypeId()
            );
        insert sobj2;
    }

    @IsTest
    static void testConversione()
    {
        lead lid = [select id, FirstName, LastName, Company, Company__c, Email, FiscalCode__c, VatNumber__c, Nation__c from lead limit 1];
        account acc = [select RecordTypeId, id from account limit 1];
        Test.startTest();
        ConversioneLead.getCustomSettings();
        ConversioneLead.GetLead(lid.id);
        ConversioneLead.CheckDataLead(lid);
        ConversioneLead.checkAccount(lid);
        lid.Status = 'To contact';
        update lid;
        lid.Status = 'Demo to do';
        update lid;
        lid.Status = 'Waiting for customer';
        update lid;
        lid.Status = 'Offer to do';
        update lid;
        ConversioneLead.ConvertLead(acc.id, lid);
        Test.stopTest();
    }
}